name: Production Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Containers & Run Tests
        run: |
          cd .docker
          docker-compose up -d
          docker-compose run web nx test
          
      - name: Build for prod and bundle up
        run: |
          cd .docker
          docker-compose up -d
          docker-compose run web build:prod
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./soisy/dist"